### ISSUE TITLE
ImageRenderer / Java2DRenderer / Graphics2DRenderer

### ISSUE THREAD

**Issue by cneijenhuis** [danfickle/neoflyingsaucer#29]
Hi,
I'm looking for a solution to render HTML to images, and this fork has some improvements upon the upstream flyingsaucer that I'm excited about (CSS3, jsoup)!
Anyway, after some initial trouble (maven install failed because of some JavaDoc errors) I tried the ImageRender-example. There seem to be two ways to render the image:

**Java2DRenderer**: This unfortunately failed because the replacedElementFactory is set to null. There is currently a TODO in the code since 6e46e270ac67e70dc6a660054fbf250c2752cb49

```
Caused by: java.lang.NullPointerException: replacedElementFactory may not be null
    at org.xhtmlrenderer.layout.SharedContext.setReplacedElementFactory(SharedContext.java:611) ~[flying-saucer-core-9.0.5-SNAPSHOTX.jar:na]
    at org.xhtmlrenderer.swing.Java2DRenderer.init(Java2DRenderer.java:370) ~[flying-saucer-core-9.0.5-SNAPSHOTX.jar:na]
```

**Graphics2DRenderer**: Worked fine, however the example refers to it as the old way of doing it, and the class is in the example module whereas the Java2DRenderer is in the core module.

Could someone please explain which class I should prefer / what their differences are? If the Java2DRenderer class is preferable, I'll try to fix the issue, though I'd appreciate any pointers :)

Thanks!

**Comment by danfickle** [comment]
Sorry about that. The referenced commit should fix that error. I'd recommend using the Java2DRenderer if you can get it working. The Graphics2DRenderer uses a Swing panel and so is heavier.

I have to warn you, I don't think this fork is ready for prime-time yet. The major problem is the lack of tests (I'm working on these at the moment).

If you do go ahead using it, please test it well for your useage case. If it doesn't turn out, you could consider using the Jsoup-to-w3c-dom conversion code with the original flyingsaucer. Although it doesn't have any CSS3, it will also have fewer intorduced errors at this point.

Anyway, thanks for the interest in the project and let us know if you get it working, or have other issues.

**Comment by cneijenhuis** [comment]
Cool, thanks! Works fine now. :+1: 
I did some un-scientific benchmarks and didn't notice a difference between either of the two renderers. As with my previous experiments in rendering (rather simple) images with Swing, most of the time is spent converting the BufferedImage to a PNG or JPG and writing it to HDD, anyways...

Thanks for the heads up! I'll only use it for HTML generated by my own code, which only differs in text and images used. No problems so far.
