### ISSUE TITLE
Support for CSS3

### ISSUE THREAD

**Issue by hrj** [danfickle/neoflyingsaucer#7]
@habermann24 has done some very good work on the upstream branch:

https://github.com/flyingsaucerproject/flyingsaucer/pull/22

Are these changes aligned with your direction, and do you think you can pull it into your fork? The changes seem to be straightforward, but there are merge conflicts (because of the switch to Java 1.5, etc).

If you are fine with the changes but don't have time to merge, I can volunteer to do the merge.

**Comment by danfickle** [comment]
Those changes are already merged and working for Java2D and Swing. See done list in readme. I haven't been able to get gradients and opacity working correctly in PDFs. Also see the gradients demo in the demo browser.

**Comment by hrj** [comment]
Oh cool! Had missed it somehow.
