### ISSUE TITLE
Proposed cleanups

### ISSUE THREAD

**Issue by hrj** [danfickle/neoflyingsaucer#9]
@danfickle What do you think of these proposals:
- [x] Use [enhanced for-loops](http://leepoint.net/notes-java/flow/loops/foreach.html)
- [x] Remove the log comments at the bottom of files. These seem to be relics from CVS era.
- [x] Move files in `com.github.danfickle.flyingsaucer.swing.test` package which are currently under `src/main/java` into `src/test/java`
- [x] Use `final` wherever possible

If you are fine with it, I will attempt them myself.

**Comment by danfickle** [comment]
I enthusiastically agree. Go for it!

**Comment by hrj** [comment]
Added one more idea for `final`. 

(Not sure if github sends notifications for edits.)

**Comment by danfickle** [comment]
I'm not a big fan of using final everywhere. I think it adds a lot of verbosity for little benefit.

**Comment by hrj** [comment]
Hmm, I am very fond of keeping immutable state wherever possible. Yes `final` is very verbose compared to alternative languages like Haskell / Scala, but `final` is what we have in Java.

Are you strongly opposed to it? In that case I won't bother making a PR for it.

**Comment by danfickle** [comment]
No, I'm not strongly opposed. If you wish to do the work, I'll certainly merge it. Thanks again for your work on this project. I hope to do some work of my own on the project in the near future. If you have any priority areas for me feel free to file an issue or comment.

**Comment by hrj** [comment]
cool; I am working on the `final` changes now.

About the future, I am still trying to find my bearings with the project. Will let you know as soon as I figure out. Thanks!
